name: Bug Report
description: Report a bug occurring while using this module.
title: "[Bug]: "
labels:
  - bug
assignees:
  - claudiospizzi
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? And how can we reproduce the error?
      placeholder: Tell us what you see!
      value: A bug happened!
    validations:
      required: true
  - type: input
    id: module-version
    attributes:
      label: Module Version
      description: Specify the used version of this module
    validations:
      required: true
  - type: input
    id: nodered-version
    attributes:
      label: Node-RED Version
      description: Specify the Node-RED version
    validations:
      required: true
  - type: input
    id: nodejs-version
    attributes:
      label: Node.JS Version
      description: Specify the Node.JS version
    validations:
      required: false
  - type: input
    id: platform-version
    attributes:
      label: Platform/OS
      description: Specify the Platform and/or Operating System
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: Browser
      description: Specify the Browser
    validations:
      required: false
