name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: ${{ github.repository.name }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ github.repository.name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.repository.name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Run Lint
        run: npm run lint
